# Generated by Django 3.1.4 on 2021-01-03 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=100)),
                ('endereco', models.CharField(help_text='Ex: Nome da rua, número - Cidade, UF, CEP', max_length=100)),
                ('telefone', models.CharField(help_text='formato: (+55) + número do código da região + número telefônico', max_length=14)),
                ('data_nascimento', models.DateField(help_text='formato: dd/mm/aaaa')),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
